num_nodes: 1
devices: 8
accelerator: gpu
precision: bf16-mixed

dpo:
    max_epochs: 2
    max_steps: -1

    val_check_interval: 200
    save_interval: 200

    limit_train_batches: 1.0
    limit_val_batches: 1.0
    gradient_clip_val: 1.0

# do not change these
logger: False # logger provided by exp_manager
enable_checkpointing: False
use_distributed_sampler: False
max_time: null

max_epochs: ${.dpo.max_epochs}
max_steps: ${.dpo.max_steps}
